version: "3.8"

services:
  minio-server:
    image: bitnami/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  create-bucket:
    image: minio/mc
    container_name: create-bucket
    depends_on:
      - minio-server
    entrypoint:
      /bin/sh -c "
      /usr/bin/mc config host add modelardata-minio http://minio-server:9000 minioadmin minioadmin;
      /usr/bin/mc mb modelardata-minio/modelardata;
      exit 0;
      "
