name: Cargo Build, Lint, and Test

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  cargo_build_lint_and_test:
    name: Cargo Build, Lint, and Test

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Rustup Update
      run: rustup update
    - name: Cargo Install
      run: cargo install cargo-machete
    - name: Cargo Build
      run: cargo build --verbose --all-targets
    - name: Cargo Clippy
      run: cargo clippy --verbose --all-targets
    - name: Cargo Doc
      run: cargo doc --verbose
    - name: Cargo Machete --with-metadata
      run: cargo machete --with-metadata
    - name: Cargo Test
      run: cargo test --verbose --all-targets
