name: Python unittest

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  python_unittest:
    name: Python unittest

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Update pip
      run: python3 -m pip install pip --force-reinstall
    - name: Install modelardb_compression_python
      run: python3 -m pip install .
      working-directory: crates/modelardb_compression_python
    - name: Python unittest
      run: python3 -m unittest --verbose
      working-directory: crates/modelardb_compression_python
